[package]
name = "bench-snarkblock"
version = "0.1.0"
edition = "2021"

[dependencies]
snarkblock = { git = "https://github.com/rozbb/snarkblock", features = ["asm", "parallel", "benchmarking"] }

rayon = "1.5"
thiserror = "1"

[patch."https://github.com/rozbb/snarkblock"]
hiciap = { git = "https://github.com/rozbb/hiciap" }


[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[profile.release]
debug = true

[lib]
bench = false

[[bench]]
name = "bench"
harness = false
